"""Generate additive easy-mode bonuses for the military reform dynamic spirits.

The normal modifiers remain untouched. A companion modifier copies only the
beneficial half of each current variable, so an existing save can switch modes
without changing the underlying military reform progression or its penalties.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "common/dynamic_modifiers/RUS_fr_military_reform_dynamic_modifiers.txt"
TARGET_MODIFIERS = ROOT / "common/dynamic_modifiers/RUS_easy_mode_military_bonus.txt"
TARGET_EFFECTS = ROOT / "common/scripted_effects/RUS_easy_mode_military_effects.txt"

# A negative value in these modifier fields helps the player. Other modifier
# fields in this source help the player when their values are positive.
NEGATIVE_IS_BENEFICIAL = {
    "training_time_army_factor",
    "supply_consumption_factor",
    "attrition",
    "combat_width_factor",
    "experience_loss_factor",
    "army_intel_to_others",
    "consumer_goods_factor",
}


def definitions() -> list[tuple[str, str, list[tuple[str, str]]]]:
    source = SOURCE.read_text(encoding="utf-8-sig")
    results = []
    for match in re.finditer(r"(?m)^(RUS_fr_\w+)\s*=\s*\{([^{}]*)\}", source):
        name, body = match.groups()
        icon = re.search(r"(?m)^\s*icon\s*=\s*(\S+)", body)
        values = re.findall(r"(?m)^\s*([a-zA-Z_]+)\s*=\s*(RUS_fr_[a-zA-Z_]+)\s*$", body)
        values = [(modifier, variable) for modifier, variable in values if modifier != "custom_modifier_tooltip"]
        if values:
            results.append((name, icon.group(1) if icon else "GFX_idea_FOP_revolutionary_army", values))
    return results


def render() -> tuple[str, str]:
    modifiers = ["# Generated by tools/generate_easy_mode_military.py."]
    effects = ["# Generated by tools/generate_easy_mode_military.py.", "", "RUS_easy_mode_refresh_military = {"]
    for name, icon, values in definitions():
        bonus = f"{name}_easy_bonus"
        modifiers.extend([f"{bonus} = {{", f"\ticon = {icon}"])
        for modifier, variable in values:
            modifiers.append(f"\t{modifier} = RUS_easy_mode_bonus_{variable}")
        modifiers.extend(["}", ""])

        effects.extend([
            "\tif = {",
            f"\t\tlimit = {{ has_country_flag = RUS_easy_mode_enabled is_ai = no has_dynamic_modifier = {{ modifier = {name} }} }}",
        ])
        for modifier, variable in values:
            mirror = f"RUS_easy_mode_bonus_{variable}"
            operator = "<" if modifier in NEGATIVE_IS_BENEFICIAL else ">"
            effects.extend([
                f"\t\tset_variable = {{ {mirror} = 0 }}",
                f"\t\tif = {{ limit = {{ check_variable = {{ {variable} {operator} 0 }} }} set_variable = {{ {mirror} = var:{variable} }} }}",
            ])
        effects.extend([
            f"\t\tif = {{ limit = {{ NOT = {{ has_dynamic_modifier = {{ modifier = {bonus} }} }} }} add_dynamic_modifier = {{ modifier = {bonus} }} }}",
            "\t}",
            "\telse = {",
            f"\t\tif = {{ limit = {{ has_dynamic_modifier = {{ modifier = {bonus} }} }} remove_dynamic_modifier = {{ modifier = {bonus} }} }}",
            "\t}",
        ])
    effects.extend(["\tforce_update_dynamic_modifier = yes", "}", ""])
    return "\n".join(modifiers) + "\n", "\n".join(effects)


def render_outputs() -> dict[str, str]:
    first, effects = render()
    return {
        "common/dynamic_modifiers/RUS_easy_mode_military_bonus.txt": first,
        "common/scripted_effects/RUS_easy_mode_military_effects.txt": effects,
    }


def main() -> None:
    from generation_io import cli
    cli(render_outputs, root=ROOT, description=__doc__, kr_dependency=False)


if __name__ == "__main__":
    main()
