"""Generate bonus-only technologies for positive modded equipment statistics."""

from __future__ import annotations

from pathlib import Path

from hoi4_politics_blocks import load


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "common/technologies"
BENEFICIAL_POSITIVE = {"soft_attack", "hard_attack", "breakthrough", "ap_attack", "max_organisation", "max_strength", "attack"}
BENEFICIAL_NEGATIVE = {"supply_consumption", "supply_consumption_factor", "fuel_consumption_factor"}


def render_stat(node, depth: int = 0) -> list[str]:
    indent = "\t" * depth
    if isinstance(node.v, list):
        children = [line for child in node.v for line in render_stat(child, depth + 1)]
        return [f"{indent}{node.k} = {{", *children, f"{indent}}}"] if children else []
    if node.k not in BENEFICIAL_POSITIVE | BENEFICIAL_NEGATIVE:
        return []
    try:
        number = float(node.v)
    except (TypeError, ValueError):
        return []
    if (number > 0 and node.k in BENEFICIAL_POSITIVE) or (number < 0 and node.k in BENEFICIAL_NEGATIVE):
        return [f"{indent}{node.k} = {node.v}"]
    return []


def render() -> tuple[str, str]:
    technology_lines = ["# Generated by tools/generate_easy_mode_technologies.py.", "technologies = {"]
    effect_lines = ["# Generated by tools/generate_easy_mode_technologies.py.", "RUS_easy_mode_refresh_technologies = {"]
    for path in sorted(SOURCE.glob("*.txt")):
        if path.name.startswith("RUS_easy_mode"):
            continue
        for root in load(path):
            if root.k != "technologies":
                continue
            for technology in root.v:
                stats = [line for child in technology.v for line in render_stat(child, 2)]
                if not stats:
                    continue
                bonus = f"{technology.k}_easy_bonus"
                technology_lines.extend([f"\t{bonus} = {{", "\t\tallow = { always = no }", *stats, "\t}", ""])
                effect_lines.extend([
                    "\tif = {",
                    f"\t\tlimit = {{ has_country_flag = RUS_easy_mode_enabled is_ai = no has_tech = {technology.k} NOT = {{ has_tech = {bonus} }} }}",
                    f"\t\tset_technology = {{ {bonus} = 1 popup = no }}",
                    "\t}",
                ])
    technology_lines.extend(["}", ""])
    effect_lines.extend(["}", ""])
    return "\n".join(technology_lines), "\n".join(effect_lines)


def render_outputs() -> dict[str, str]:
    first, effects = render()
    return {
        "common/technologies/RUS_easy_mode_bonus_technologies.txt": first,
        "common/scripted_effects/RUS_easy_mode_technologies_effects.txt": effects,
    }


def main() -> None:
    from generation_io import cli
    cli(render_outputs, root=ROOT, description=__doc__, kr_dependency=False)


if __name__ == "__main__":
    main()
