"""Add country-level copies of positive values on changed advisor traits.

Relationship-tier traits have their own native easy variants and are excluded.
This handles other hired political, military, and second-in-command advisers.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from generate_relationship_advisor_tiers import easy_modifier_value
from hoi4_politics_blocks import load


ROOT = Path(__file__).resolve().parents[1]
from kr_generation_baseline import kr_root


def traits(folder: Path):
    return {trait.k: trait for path in folder.glob("*.txt") for root in load(path) if root.k == "leader_traits" for trait in root.v}


def walk(nodes):
    for node in nodes:
        yield node
        if isinstance(node.v, list):
            yield from walk(node.v)


def advisor_roles():
    roles = defaultdict(list)
    for path in (ROOT / "common/characters").glob("*.txt"):
        for root in load(path):
            if root.k != "characters":
                continue
            for character in root.v:
                for advisor in character.children("advisor"):
                    slot = advisor.value("slot")
                    token = advisor.value("idea_token")
                    if not slot or not token:
                        continue
                    initial = advisor.one("traits")
                    for trait in initial.v if initial else []:
                        roles[(character.k, slot)].append((token, trait.k))
    for folder in (ROOT / "common/scripted_effects", ROOT / "common/decisions", ROOT / "events"):
        for path in folder.glob("*.txt"):
            if path.name.startswith("RUS_easy_mode"):
                continue
            for node in walk(load(path)):
                if node.k == "add_trait" and isinstance(node.v, list):
                    character, slot, trait = (node.value(key) for key in ("character", "slot", "trait"))
                    for token, _ in roles.get((character, slot), []):
                        roles[(character, slot)].append((token, trait))
                        break
    return roles


def data():
    old = traits(kr_root(ROOT) / "common/country_leader")
    current = traits(ROOT / "common/country_leader")
    changed = {key: trait for key, trait in current.items() if not key.startswith("RUS_relationship_scaled_") and (key not in old or trait.norm() != old[key].norm())}
    bonuses = []
    for (character, slot), entries in advisor_roles().items():
        for token, name in set(entries):
            trait = changed.get(name)
            if not trait:
                continue
            values = {}
            for node in trait.v:
                if isinstance(node.v, list) or node.k in ("sprite", "random"):
                    continue
                try:
                    amount = float(node.v)
                except (TypeError, ValueError):
                    continue
                if easy_modifier_value(node.k, amount) != amount:
                    values[node.k] = node.v
            if values:
                bonuses.append((character, token, name, values))
    return sorted(bonuses)


def render() -> tuple[str, str]:
    entries = data()
    keys = sorted({key for _, _, _, values in entries for key in values})
    modifiers = ["# Generated by tools/generate_easy_mode_advisors.py.", "RUS_easy_mode_advisor_bonus = {", "\ticon = GFX_idea_generic_political_reform"]
    modifiers.extend(f"\t{key} = RUS_easy_advisor_{key}" for key in keys)
    modifiers.extend(["}", ""])
    effects = ["# Generated by tools/generate_easy_mode_advisors.py.", "RUS_easy_mode_refresh_advisors = {", "\tset_variable = { RUS_easy_advisor_active = 0 }"]
    effects.extend(f"\tset_variable = {{ RUS_easy_advisor_{key} = 0 }}" for key in keys)
    for character, token, trait, values in entries:
        effects.extend([
            "\tif = {",
            f"\t\tlimit = {{ has_idea = {token} has_character = {character} {character} = {{ has_trait = {trait} }} }}",
            "\t\tadd_to_variable = { RUS_easy_advisor_active = 1 }",
        ])
        effects.extend(f"\t\tadd_to_variable = {{ RUS_easy_advisor_{key} = {amount} }}" for key, amount in values.items())
        effects.append("\t}")
    effects.extend([
        "\tif = {",
        "\t\tlimit = { has_country_flag = RUS_easy_mode_enabled is_ai = no check_variable = { RUS_easy_advisor_active > 0 } }",
        "\t\tif = { limit = { NOT = { has_dynamic_modifier = { modifier = RUS_easy_mode_advisor_bonus } } } add_dynamic_modifier = { modifier = RUS_easy_mode_advisor_bonus } }",
        "\t}",
        "\telse = {",
        "\t\tif = { limit = { has_dynamic_modifier = { modifier = RUS_easy_mode_advisor_bonus } } remove_dynamic_modifier = { modifier = RUS_easy_mode_advisor_bonus } }",
        "\t}",
        "\tforce_update_dynamic_modifier = yes",
        "}",
        "",
    ])
    return "\n".join(modifiers) + "\n", "\n".join(effects)


def render_outputs() -> dict[str, str]:
    first, effects = render()
    return {
        "common/dynamic_modifiers/RUS_easy_mode_advisor_bonus.txt": first,
        "common/scripted_effects/RUS_easy_mode_advisor_effects.txt": effects,
    }


def main() -> None:
    from generation_io import cli
    cli(render_outputs, root=ROOT, description=__doc__, kr_dependency=True)


if __name__ == "__main__":
    main()
