"""Generate a single bonus modifier for the mod's own national spirits.

The inherited RUS ideas (Russia).txt is deliberately excluded. Values from
the other idea files are recomputed from active ideas, so timed ideas and old
saves require no destructive swaps or reward replays.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from hoi4_politics_blocks import load


ROOT = Path(__file__).resolve().parents[1]
from kr_generation_baseline import kr_root
IDEAS = ROOT / "common/ideas"
TARGET_MODIFIERS = ROOT / "common/dynamic_modifiers/RUS_easy_mode_ideas_bonus.txt"
TARGET_EFFECTS = ROOT / "common/scripted_effects/RUS_easy_mode_ideas_effects.txt"

# An on_remove callback may run while has_idea is still true. These short-lived
# guards let that callback rebuild the aggregate without its expiring benefit.
REMOVAL_FLAGS = {
    "RUS_aiding_chinese_comrades": "RUS_china_mission_removing",
    "RUS_northeast_anti_japanese_network": "RUS_northeast_network_removing",
    "RUS_transcontinental_economic_cooperation": "RUS_transcontinental_cooperation_removing",
    "RUS_workers_peasants_military_exchange": "RUS_military_exchange_removing",
    "RUS_project_156_recipient": "RUS_project_156_recipient_removing",
    "RUS_sino_soviet_friendship_treaty": "RUS_sino_soviet_treaty_removing",
}

# Hostile political agitation is a penalty, not a benefit for an easy-mode Japan.
EXCLUDED_IDEAS = {"RUS_japanese_antiwar_movement"}

NEGATIVE_IS_BENEFICIAL = {
    "air_fuel_consumption_factor",
    "aircraft_manufacturer_cost_factor",
    "army_intel_to_others",
    "attrition",
    "combat_width_factor",
    "consumer_goods_expected_value",
    "consumer_goods_factor",
    "conversion_cost_civ_to_mil_factor",
    "conversion_cost_mil_to_civ_factor",
    "economy_cost_factor",
    "experience_loss_factor",
    "factory_energy_consumption",
    "fuel_consumption",
    "industrial_concern_cost_factor",
    "land_doctrine_cost_factor",
    "materiel_manufacturer_cost_factor",
    "naval_manufacturer_cost_factor",
    "production_cost_arms_factory_factor",
    "production_cost_industrial_complex_factor",
    "production_lack_of_resource_penalty_factor",
    "supply_consumption_factor",
    "tank_manufacturer_cost_factor",
    "training_time_army_factor",
    "truck_attrition_factor",
}


def is_beneficial(key: str, value: float) -> bool:
    return value < 0 if key in NEGATIVE_IS_BENEFICIAL else value > 0


def bonuses() -> dict[str, dict[str, list[str]]]:
    result = defaultdict(lambda: defaultdict(list))
    for path in sorted(IDEAS.glob("*.txt")):
        upstream = kr_root(ROOT) / path.relative_to(ROOT)
        upstream_ideas = {}
        if upstream.exists():
            for old_root in load(upstream):
                if old_root.k == "ideas" and isinstance(old_root.v, list):
                    for old_category in old_root.v:
                        if isinstance(old_category.v, list):
                            upstream_ideas.update({idea.k: idea.norm() for idea in old_category.v if isinstance(idea.v, list)})
        for root in load(path):
            if root.k != "ideas" or not isinstance(root.v, list):
                continue
            for category in root.v:
                if not isinstance(category.v, list):
                    continue
                for idea in category.v:
                    if not isinstance(idea.v, list):
                        continue
                    if idea.k in EXCLUDED_IDEAS:
                        continue
                    if upstream_ideas.get(idea.k) == idea.norm():
                        continue
                    for block in idea.children("modifier") + idea.children("hidden_modifier"):
                        for value in block.v:
                            if isinstance(value.v, list) or value.k == "custom_modifier_tooltip":
                                continue
                            try:
                                number = float(value.v)
                            except (ValueError, TypeError):
                                continue
                            if is_beneficial(value.k, number):
                                result[idea.k][value.k].append(value.v)
    return result


def render() -> tuple[str, str]:
    found = bonuses()
    keys = sorted({key for modifiers in found.values() for key in modifiers})
    modifiers = ["# Generated by tools/generate_easy_mode_ideas.py.", "RUS_easy_mode_ideas_bonus = {", "\ticon = GFX_idea_generic_industry"]
    modifiers.extend(f"\t{key} = RUS_easy_mode_idea_{key}" for key in keys)
    modifiers.extend(["}", ""])

    effects = ["# Generated by tools/generate_easy_mode_ideas.py.", "RUS_easy_mode_refresh_ideas = {", "\tset_variable = { RUS_easy_mode_active_idea_count = 0 }"]
    effects.extend(f"\tset_variable = {{ RUS_easy_mode_idea_{key} = 0 }}" for key in keys)
    for idea, values in sorted(found.items()):
        condition = f"has_idea = {idea}"
        if idea in REMOVAL_FLAGS:
            condition += f" NOT = {{ has_country_flag = {REMOVAL_FLAGS[idea]} }}"
        effects.extend(["\tif = {", f"\t\tlimit = {{ {condition} }}", "\t\tadd_to_variable = { RUS_easy_mode_active_idea_count = 1 }"])
        for key, numbers in sorted(values.items()):
            for number in numbers:
                effects.append(f"\t\tadd_to_variable = {{ RUS_easy_mode_idea_{key} = {number} }}")
        effects.append("\t}")
    effects.extend([
        "\tif = {",
        "\t\tlimit = { has_country_flag = RUS_easy_mode_enabled is_ai = no check_variable = { RUS_easy_mode_active_idea_count > 0 } }",
        "\t\tif = { limit = { NOT = { has_dynamic_modifier = { modifier = RUS_easy_mode_ideas_bonus } } } add_dynamic_modifier = { modifier = RUS_easy_mode_ideas_bonus } }",
        "\t}",
        "\telse = {",
        "\t\tif = { limit = { has_dynamic_modifier = { modifier = RUS_easy_mode_ideas_bonus } } remove_dynamic_modifier = { modifier = RUS_easy_mode_ideas_bonus } }",
        "\t}",
        "\tforce_update_dynamic_modifier = yes",
        "}",
        "",
    ])
    return "\n".join(modifiers) + "\n", "\n".join(effects)


def render_outputs() -> dict[str, str]:
    first, effects = render()
    return {
        "common/dynamic_modifiers/RUS_easy_mode_ideas_bonus.txt": first,
        "common/scripted_effects/RUS_easy_mode_ideas_effects.txt": effects,
    }


def main() -> None:
    from generation_io import cli
    cli(render_outputs, root=ROOT, description=__doc__, kr_dependency=True)


if __name__ == "__main__":
    main()
