"""Generate bonus-only technologies for positive modded equipment statistics."""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

from hoi4_politics_blocks import load


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "common/technologies"
BENEFICIAL_POSITIVE = {"soft_attack", "hard_attack", "breakthrough", "ap_attack", "max_organisation", "max_strength", "attack"}
BENEFICIAL_NEGATIVE = {"supply_consumption", "supply_consumption_factor", "fuel_consumption_factor"}
VDV_UNIT = "air_assault_special_forces"
VDV_UNLOCK = "RUS_stalin_air_assault_special_forces_infantry"
VDV_BASE_BONUS = "RUS_easy_mode_air_assault_base_bonus"
VDV_EXTRA_COPIES = Decimal(9)


def number_text(number: Decimal) -> str:
    return format(number, "f").rstrip("0").rstrip(".") if "." in format(number, "f") else str(number)


def render_vdv_base_bonus() -> list[str]:
    """Add nine copies of the normal battalion, without changing its costs.

    Equipment-derived combat stats are factors (the implicit 1 matters);
    strength, organisation, recovery, initiative and width are flat unit stats.
    Terrain is explicitly +50% -> +500%, not a tenfold final terrain multiplier.
    """
    units = load(ROOT / "common/units/RUS_stalin_air_assault.txt")[0]
    unit = units.one(VDV_UNIT)
    assert unit is not None
    lines = [f"\t{VDV_BASE_BONUS} = {{", "\t\tallow = { always = no }", f"\t\t{VDV_UNIT} = {{"]
    for key in ("soft_attack", "hard_attack", "defense", "breakthrough", "ap_attack", "air_attack", "armor_value", "maximum_speed"):
        extra = (1 + Decimal(unit.value(key, "0"))) * VDV_EXTRA_COPIES
        lines.append(f"\t\t\t{key} = {number_text(extra)}")
    for key in ("max_strength", "max_organisation", "default_morale", "initiative"):
        extra = Decimal(unit.value(key, "0")) * VDV_EXTRA_COPIES
        if extra:
            lines.append(f"\t\t\t{key} = {number_text(extra)}")
    lines.append(f"\t\t\tcombat_width = {number_text(Decimal(1) - Decimal(unit.value('combat_width')))}")
    for terrain in ("plains", "forest", "hills", "mountain", "jungle", "marsh", "desert", "urban"):
        values = unit.one(terrain)
        assert values is not None
        lines.append(f"\t\t\t{terrain} = {{")
        for key in ("attack", "defence", "movement"):
            extra = Decimal(values.value(key)) * VDV_EXTRA_COPIES
            lines.append(f"\t\t\t\t{key} = {number_text(extra)}")
        lines.append("\t\t\t}")
    return [*lines, "\t\t}", "\t}", ""]


def render_stat(node, depth: int = 0, vdv: bool = False) -> list[str]:
    indent = "\t" * depth
    if isinstance(node.v, list):
        children = [line for child in node.v for line in render_stat(child, depth + 1, vdv or node.k == VDV_UNIT)]
        return [f"{indent}{node.k} = {{", *children, f"{indent}}}"] if children else []
    if node.k not in BENEFICIAL_POSITIVE | BENEFICIAL_NEGATIVE:
        return []
    try:
        number = float(node.v)
    except (TypeError, ValueError):
        return []
    if (number > 0 and node.k in BENEFICIAL_POSITIVE) or (number < 0 and node.k in BENEFICIAL_NEGATIVE):
        value = number_text(Decimal(node.v) * VDV_EXTRA_COPIES) if vdv and node.k in BENEFICIAL_POSITIVE else node.v
        return [f"{indent}{node.k} = {value}"]
    return []


def render() -> tuple[str, str]:
    technology_lines = ["# Generated by tools/generate_easy_mode_technologies.py.", "technologies = {"]
    effect_lines = ["# Generated by tools/generate_easy_mode_technologies.py.", "RUS_easy_mode_refresh_technologies = {"]
    technology_lines.extend(render_vdv_base_bonus())
    effect_lines.extend([
        "\tif = {",
        f"\t\tlimit = {{ has_country_flag = RUS_easy_mode_enabled is_ai = no has_tech = {VDV_UNLOCK} NOT = {{ has_tech = {VDV_BASE_BONUS} }} }}",
        f"\t\tset_technology = {{ {VDV_BASE_BONUS} = 1 popup = no }}",
        "\t}",
    ])
    for path in sorted(SOURCE.glob("*.txt")):
        if path.name.startswith("RUS_easy_mode"):
            continue
        for root in load(path):
            if root.k != "technologies":
                continue
            for technology in root.v:
                stats = [line for child in technology.v for line in render_stat(child, 2)]
                if not stats:
                    continue
                bonus = f"{technology.k}_easy_bonus"
                technology_lines.extend([f"\t{bonus} = {{", "\t\tallow = { always = no }", *stats, "\t}", ""])
                effect_lines.extend([
                    "\tif = {",
                    f"\t\tlimit = {{ has_country_flag = RUS_easy_mode_enabled is_ai = no has_tech = {technology.k} NOT = {{ has_tech = {bonus} }} }}",
                    f"\t\tset_technology = {{ {bonus} = 1 popup = no }}",
                    "\t}",
                ])
    technology_lines.extend(["}", ""])
    effect_lines.extend(["}", ""])
    return "\n".join(technology_lines), "\n".join(effect_lines)


def render_outputs() -> dict[str, str]:
    first, effects = render()
    return {
        "common/technologies/RUS_easy_mode_bonus_technologies.txt": first,
        "common/scripted_effects/RUS_easy_mode_technologies_effects.txt": effects,
    }


def main() -> None:
    from generation_io import cli
    cli(render_outputs, root=ROOT, description=__doc__, kr_dependency=False)


if __name__ == "__main__":
    main()
