"""Generate easy-mode companions for mod-owned dynamic modifiers.

The military-reform spirits and current Kamenev balance have dedicated logic.
Other active dynamic modifiers gain an additive copy of each beneficial field.
"""

from __future__ import annotations

from pathlib import Path
import re

from hoi4_politics_blocks import load


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILES = [
    "RUS stalin dynamic_modifiers.txt",
    "RUS_future_foreign_policy_dynamic_modifiers.txt",
    "RUS_kamenev_politics_modifiers.txt",
    "RUS_national_agriculture_modifiers.txt",
]
SKIP = {"RUS_kamenev_party_balance_modifier", "RUS_soviet_union_integration_strain"}
NEGATIVE_IS_BENEFICIAL = {
    "consumer_goods_factor", "consumer_goods_expected_value", "supply_consumption_factor",
    "attrition", "factory_energy_consumption", "production_lack_of_resource_penalty_factor",
    "production_cost_arms_factory_factor", "military_industrial_organization_policy_cost",
    "political_advisor_cost_factor", "improve_relations_maintain_cost_factor",
    "training_time_army_factor", "experience_loss_factor", "resistance_target",
    "resistance_damage_to_garrison", "army_intel_to_others", "civilian_factory_use",
    "river_crossing_factor",
}
STATE_PREFIXES = ("local_", "state_")


def is_state_modifier(nodes) -> bool:
    return any(node.k.startswith(STATE_PREFIXES) for node in nodes)


def render() -> tuple[str, str]:
    modifier_lines = ["# Generated by tools/generate_easy_mode_dynamic.py."]
    country_effect = ["RUS_easy_mode_refresh_other_dynamic = {"]
    state_effect = ["RUS_easy_mode_refresh_state_dynamic = {"]
    for filename in SOURCE_FILES:
        for source in load(ROOT / "common/dynamic_modifiers" / filename):
            if source.k in SKIP or not isinstance(source.v, list):
                continue
            values = [node for node in source.v if not isinstance(node.v, list) and node.k not in ("icon", "custom_modifier_tooltip")]
            values = [node for node in values if isinstance(node.v, str) and (node.v.startswith("RUS_") or node.v.startswith("vst_") or _number(node.v) is not None)]
            if not values:
                continue
            is_state = is_state_modifier(values)
            effect = state_effect if is_state else country_effect
            bonus = f"{source.k}_easy_bonus"
            icon = source.value("icon", "GFX_idea_generic_industry")
            entry_lines = [f"{bonus} = {{", f"\ticon = {icon}"]
            assignments = []
            for node in values:
                numeric = _number(node.v)
                if numeric is not None:
                    if (numeric < 0) == (node.k in NEGATIVE_IS_BENEFICIAL) and numeric != 0:
                        entry_lines.append(f"\t{node.k} = {node.v}")
                    continue
                mirror = f"RUS_easy_dyn_{source.k}_{node.k}"
                entry_lines.append(f"\t{node.k} = {mirror}")
                direction = "<" if node.k in NEGATIVE_IS_BENEFICIAL else ">"
                assignments.extend([
                    f"\t\tset_variable = {{ {mirror} = 0 }}",
                    f"\t\tif = {{ limit = {{ check_variable = {{ {node.v} {direction} 0 }} }} set_variable = {{ {mirror} = var:{node.v} }} }}",
                ])
            if len(entry_lines) == 2:
                continue
            modifier_lines.extend(entry_lines + ["}", ""])
            enable = source.one("enable")
            if enable:
                trigger = enable.inner().strip()
            else:
                trigger = f"has_dynamic_modifier = {{ modifier = {source.k} }}"
            if source.k == "RUS_nat_industry":
                trigger += " NOT = { has_country_flag = RUS_nat_system_closed }"
            player = "owner = { has_country_flag = RUS_easy_mode_enabled is_ai = no }" if is_state else "has_country_flag = RUS_easy_mode_enabled is_ai = no"
            effect.extend([
                "\tif = {",
                f"\t\tlimit = {{ {player} {trigger} }}",
                *assignments,
                f"\t\tif = {{ limit = {{ NOT = {{ has_dynamic_modifier = {{ modifier = {bonus} }} }} }} add_dynamic_modifier = {{ modifier = {bonus} }} }}",
                "\t}",
                "\telse = {",
                f"\t\tif = {{ limit = {{ has_dynamic_modifier = {{ modifier = {bonus} }} }} remove_dynamic_modifier = {{ modifier = {bonus} }} }}",
                "\t}",
            ])
    country_effect.extend(["\tforce_update_dynamic_modifier = yes", "}", ""])
    state_effect.extend(["\tforce_update_dynamic_modifier = yes", "}", ""])
    return "\n".join(modifier_lines) + "\n", "\n".join(country_effect + state_effect)


def _number(value: str) -> float | None:
    try:
        return float(value)
    except ValueError:
        return None


def render_outputs() -> dict[str, str]:
    modifiers, effects = render()
    outputs = {
        "common/dynamic_modifiers/RUS_easy_mode_other_dynamic_bonus.txt": modifiers,
        "common/scripted_effects/RUS_easy_mode_other_dynamic_effects.txt": effects,
    }
    names = re.findall(r"(?m)^(RUS_\w+)_easy_bonus =", modifiers)
    suffixes = {"simp_chinese": ("：", "简易模式增益"), "english": (" — ", "Easy Mode Bonus"), "russian": (" — ", "Бонус упрощённого режима")}
    for language, (separator, suffix) in suffixes.items():
        lines = [f"l_{language}:"]
        lines.extend(f' {name}_easy_bonus:0 "${name}${separator}{suffix}"' for name in names)
        outputs[f"localisation/{language}/RUS_easy_mode_dynamic_l_{language}.yml"] = "\n".join(lines) + "\n"
    return outputs


def main() -> None:
    from generation_io import cli
    cli(render_outputs, root=ROOT, description=__doc__)


if __name__ == "__main__":
    main()
