// Reusable guidance and player notifications; all rewards stay in settlement effects.
module.exports = ({label: register,write}) => {
  // Event paper needs black figures; keep colored terms and protected UI references intact.
  const blackNumbers = text => text.replace(/§[^!](.*?)§!/g, (token, body) =>
    /^(?:[+\-\d.,%—–/ ]|\[\?[^\]]+\])+$/.test(body) ? `§b${body}§!` : token
  ).replace(/§[^!].*?§!|£[^£]+£|\[[^\]]+\]|[+-]?\d+(?:[.,]\d+)?%?/g,
    token => /^(?:[+-]?\d|\[\?)/.test(token) ? `§b${token}§!` : token);
  const label = (key, ...values) => register(key, ...values.map(t => {
    const text = t.replace(/\n/g, '\\n').replace('§Y[GetRUSNatPlan]§!', '[GetRUSNatPlan]');
    return /^RUS_national_agriculture\.\d+\.d$/.test(key) ? blackNumbers(text).replace(/§Y/g, '§b') : text;
  }));
  const id = n => `RUS_national_agriculture.${n}`;
  label(id(2)+'.t','国家农业经营指南','National Agriculture Guide','Руководство по сельскому хозяйству');
  label(id(2)+'.d',
    '点击农业界面顶部的§Y四个页签§!，即可切换生产、农机、贸易与报告。分类下的§Y国家农业经营指南§!决议可随时重新查阅。\n\n§4安排生产§!：每季免费配置§Y10§!，每种作物最多§Y10§!。先查看§Y供需清单§!中的内需与储备缺口，再用加减按钮分配作物。单位产量和出口收入随配置刷新。\n\n§4保存方案§!：手动调整即时保存；确认方案后锁定本季配置，重新调整可解锁。下季保留手动配置，自动模式则根据新季内需与储备重排。未确认的手动草案也会用于结算。\n\n§4推进土改§!：农业从部长任命后运行，正式启动土地改革后才获得经营积分。目标§Y200§!，期限§Y720§!天；土改决议累计最多提供§Y90§!，其余由经营与事件补足。\n\n§4季度结算§!：先满足内需，再保留储备、交付订单，最后扣除剩余库存损耗。新季度会收到通知，截止前§Y7§!天提醒检查未确认方案。',
    'Click the §Yfour tabs§! above the agriculture interface to switch between crops, machinery, trade and reports. The free §YNational Agriculture Guide§! decision reopens this guide.\n\n§4Production§!: allocate §Y10§! free points per quarter, up to §Y10§! per crop. Check the §YSupply Ledger§! for domestic and reserve gaps, then use the plus and minus buttons. Unit yields and export estimates update immediately.\n\n§4Plans§!: manual edits are saved immediately. Confirm locks this quarter; Reopen allows edits. Manual allocations carry into the next quarter. Automatic mode replans for seasonal domestic needs and reserves. An unconfirmed manual draft is still used at settlement.\n\n§4Reform§!: farming starts on appointment; reform points start with formal land reform. Reach §Y200§! in §Y720§! days. Decisions provide at most §Y90§!; farming and events supply the rest.\n\n§4Settlement§!: domestic supply, reserves, orders, then remaining-stock spoilage. A notice arrives each new quarter; unconfirmed plans receive a reminder with §Y7§! days left.',
    'Нажимайте §Yчетыре вкладки§! над аграрным интерфейсом для перехода к посевам, технике, торговле и отчёту. Бесплатное решение §YРуководство по сельскому хозяйству§! открывает эту справку повторно.\n\n§4Производство§!: §Y10§! бесплатных единиц плана на квартал, до §Y10§! на культуру. Проверьте внутренние нужды и резервы в §YБалансе§!, затем распределите посевы кнопками плюс и минус. Оценки урожая и дохода обновляются сразу.\n\n§4План§!: ручные изменения сохраняются сразу. Утверждение блокирует план; повторное открытие разрешает правки. Ручной план переносится в следующий квартал, автоматический пересчитывается по сезонным нуждам и резервам. Неутверждённый ручной план также применяется при расчёте.\n\n§4Реформа§!: хозяйство работает с назначения министра, очки выдаются после официального начала реформы. Цель §Y200§! за §Y720§! дней. Решения дают до §Y90§!, остальное — хозяйство и события.\n\n§4Расчёт§!: внутренние нужды, резервы, заказы, затем потери остатков. Каждый квартал приходит уведомление; за §Y7§! дней до конца — напоминание о неутверждённом плане.');
  label(id(3)+'.t','新一季度农业安排','A New Agricultural Quarter','Новый сельскохозяйственный квартал');
  label(id(3)+'.d',
    '上一季度已完成结算。\n\n§4内需满足§!：粮食§Y[?RUS_nat_food_last_ratio|2]%§!，甜菜§Y[?RUS_nat_beet_last_ratio|2]%§!，纺织原料§Y[?RUS_nat_textile_last_ratio|2]%§!。\n§4本次土改积分§!：§G+[?RUS_agri_last_quarter_score|2]§!。\n§4本次政治点§!：§G+[?RUS_nat_last_pp|1]§!。\n\n新季度的季节条件、预测、需求与订单已更新，手动配置已保留。请检查§Y供需清单§!，安排本季生产。',
    'The previous quarter has settled.\n\n§4Domestic supply§!: food §Y[?RUS_nat_food_last_ratio|2]%§!, beet §Y[?RUS_nat_beet_last_ratio|2]%§!, fibre §Y[?RUS_nat_textile_last_ratio|2]%§!.\n§4Reform points§!: §G+[?RUS_agri_last_quarter_score|2]§!.\n§4Political power§!: §G+[?RUS_nat_last_pp|1]§!.\n\nSeasonal conditions, forecasts, needs and orders have updated. Manual allocations are retained. Check the §YSupply Ledger§! for the new quarter.',
    'Прошлый квартал рассчитан.\n\n§4Внутренние нужды§!: зерно §Y[?RUS_nat_food_last_ratio|2]%§!, свёкла §Y[?RUS_nat_beet_last_ratio|2]%§!, волокно §Y[?RUS_nat_textile_last_ratio|2]%§!.\n§4Очки реформы§!: §G+[?RUS_agri_last_quarter_score|2]§!.\n§4Политвласть§!: §G+[?RUS_nat_last_pp|1]§!.\n\nСезон, прогнозы, потребности и заказы обновлены. Ручное распределение сохранено. Проверьте §YБаланс§! нового квартала.');
  label(id(4)+'.t','本季农业方案待检查','Review the Agricultural Plan','Проверка квартального плана');
  label(id(4)+'.d',
    '距离本季结算还有§Y[?RUS_nat_remaining|0]§!天。当前状态：§Y[GetRUSNatPlan]§!。\n\n请核对内需满足率、储备与订单缺口。手动草案会按当前配置结算，自动模式按内需和储备安排。确认后可通过§Y重新调整§!继续修改。',
    'Settlement is §Y[?RUS_nat_remaining|0]§! days away. Current state: §Y[GetRUSNatPlan]§!.\n\nReview domestic coverage, reserves and orders. The current manual draft will be used; automatic mode allocates for domestic needs and reserves. A confirmed plan can be reopened.',
    'До расчёта §Y[?RUS_nat_remaining|0]§! дней. Состояние: §Y[GetRUSNatPlan]§!.\n\nПроверьте снабжение, резервы и заказы. Ручной черновик будет применён; автоплан учитывает внутренние нужды и запасы. Утверждённый план можно снова открыть.');
  label(id(5)+'.t','本季农业供需清单','Quarterly Supply Ledger','Баланс текущего квартала');
  const groups=[['food','粮食','Food','Зерно'],['beet','甜菜','Beet','Свёкла'],['textile','纺织原料','Fibre','Волокно']];
  const q=(g,k,d=1)=>`§Y[?RUS_nat_${g}_${k}|${d}]§!`;
  label(id(5)+'.d',
    groups.map(([g,zh])=>`§4${zh}§!\n现有库存 ${q(g,'stock_now')}，预计新增 ${q(g,'new_yield')}。\n内需供给 ${q(g,'delivered')}/${q(g,'need')}，满足率 ${q(g,'preview',2)}%。\n储备目标 ${q(g,'reserve')}，已接订单 ${q(g,'order_need')}。\n覆盖上述目标还需增产：§R[?RUS_nat_${g}_all_gap|2]§!。`).join('\n\n')+'\n\n总需求 = 本季内需 + 选定储备 + 已接订单\n\n粮食与纺织按类别合计，订单按指定作物整单交付。内需、出口完成后的剩余库存于本季结算时扣除损耗。预估采用公开条件。',
    groups.map(([g,,en])=>`§4${en}§!\nCurrent stock ${q(g,'stock_now')}; expected harvest ${q(g,'new_yield')}.\nDomestic supply ${q(g,'delivered')}/${q(g,'need')} (${q(g,'preview',2)}%).\nReserve target ${q(g,'reserve')}; accepted orders ${q(g,'order_need')}.\nAdditional harvest required: §R[?RUS_nat_${g}_all_gap|2]§!.`).join('\n\n')+'\n\nTotal target = domestic needs + selected reserves + accepted orders\n\nFood and fibre are grouped; orders require their specified crop in full. Remaining stocks spoil after domestic supply and exports at this quarter end. Estimates use public conditions.',
    groups.map(([g,,,ru])=>`§4${ru}§!\nЗапас ${q(g,'stock_now')}; ожидаемый урожай ${q(g,'new_yield')}.\nСнабжение ${q(g,'delivered')}/${q(g,'need')} (${q(g,'preview',2)}%).\nЦелевой резерв ${q(g,'reserve')}; заказы ${q(g,'order_need')}.\nДополнительно требуется: §R[?RUS_nat_${g}_all_gap|2]§!.`).join('\n\n')+'\n\nОбщая цель = внутренние нужды + резерв + принятые заказы\n\nЗерно и волокно объединены в группы; заказ требует указанную культуру целиком. Остатки теряются после снабжения и экспорта при расчёте текущего квартала. Прогноз использует открытые условия.');
  label('RUS_nat_event_production','查看农业生产','Review Production','Открыть производство');
  label('RUS_nat_event_ledger','查看供需清单','Open Supply Ledger','Открыть баланс');
  label('RUS_nat_event_close','继续当前安排','Continue Current Plan','Продолжить текущий план');
  label('RUS_nat_event_confirm','确认本季方案','Confirm This Plan','Утвердить план');
  label('RUS_nat_event_conditions','天气与行情是什么意思？','Weather and Market Forecasts','Погода и рыночный прогноз');
  label('RUS_nat_event_indicators','产量、地力与收入怎么看？','Yields, Soil and Income','Урожай, почва и доход');
  label('RUS_nat_event_guide','返回经营指南','Back to the Guide','Вернуться к руководству');
  label(id(6)+'.t','天气与行情','Weather and Markets','Погода и рынок');
  label(id(6)+'.d',
    '£RUS_nat_text_food£ §4天气§!代表本季全国农业气候的综合影响，五种作物共用同一结果。§G有利§!倾向增产，§Y常态§!倾向无修正，§R不利§!倾向减产。实际恶劣天气还会提高在役农机损耗。\n\n天气修正先加到季节产出系数，再计算农机覆盖等因素。例如报告中的天气§G+20%§!对应系数§G+0.20§!：\n§Y1.25§! + §G0.20§! = §Y1.45§!\n\n£RUS_nat_text_income£ §4行情§!代表出口市场的价格变化，只影响已交付订单的售价。§G偏强§!倾向涨价，§Y平稳§!倾向无修正，§R偏弱§!倾向降价。五种作物分别抽取，农机另有独立行情，预测结果可能偶然相同。\n\n§4预测与实际§!：开季显示的词语表示概率倾向。预测有利仍可能遇到坏天气，预测偏强仍可能降价。实际天气和行情到季末才在§Y季度报告§!公布。\n\n§4预估口径§!：界面的单位产量与预计出口收入仅采用公开条件，均未计入隐藏的实际天气与行情；预测词语也不会直接加进预估数字。',
    '£RUS_nat_text_food£ §4Weather§! is the quarter-wide climate outcome shared by all five crops. §GFavourable§! tends towards more output, §Ynormal§! towards no change, and §Radverse§! towards less output. Actual adverse weather also increases machinery wear.\n\nWeather is added to the seasonal yield coefficient before machinery coverage and other factors. A reported weather change of §G+20%§! adds §G0.20§! to that coefficient:\n§Y1.25§! + §G0.20§! = §Y1.45§!\n\n£RUS_nat_text_income£ §4Markets§! change the sale price of delivered export orders. §GStrong§! tends towards higher prices, §Ysteady§! towards no change and §Rweak§! towards lower prices. Each crop and machinery have separate market draws; forecasts may coincide.\n\n§4Forecasts and outcomes§!: the opening labels indicate likelihood, not certainty. Favourable weather can turn adverse; a strong market can fall. Actual outcomes appear in the §YQuarterly Report§! at settlement.\n\n§4Estimates§!: displayed unit yields and export income use public conditions only. Hidden actual weather and markets, and forecast labels themselves, are excluded from those calculations.',
    '£RUS_nat_text_food£ §4Погода§! — общий климатический итог квартала для пяти культур. §GБлагоприятная§! чаще повышает урожай, §Yобычная§! чаще не меняет его, §Rплохая§! чаще снижает. Фактическая плохая погода также повышает износ техники.\n\nПоправка погоды прибавляется к сезонному коэффициенту до учёта техники и прочих факторов. Погодные §G+20%§! в отчёте означают прибавку §G0.20§! к коэффициенту:\n§Y1.25§! + §G0.20§! = §Y1.45§!\n\n£RUS_nat_text_income£ §4Рынок§! меняет цену выполненных экспортных заказов. §GСильный§! чаще повышает цену, §Yстабильный§! чаще сохраняет её, §Rслабый§! чаще снижает. Культуры и техника имеют отдельные рыночные результаты; прогнозы могут совпасть.\n\n§4Прогноз и итог§!: начальные оценки показывают вероятность. Благоприятная погода может стать плохой, сильный рынок — упасть. Итоги раскрываются при расчёте в §YКвартальном отчёте§!.\n\n§4Оценки§!: урожай на единицу и ожидаемый экспортный доход учитывают открытые условия. Скрытые погода и рынок, как и сами слова прогноза, в эти числа не входят.');
  label(id(7)+'.t','产量、地力与收入','Yields, Soil and Income','Урожай, почва и доход');
  label(id(7)+'.d',
    '£RUS_nat_text_food£ §4单位产量§!：每配置§Y1§!所预计获得的实物作物数量，已含季节、地力疲劳、平均农机覆盖、公开农业加成及不足整季折算。\n\n预计新增产量 = 配置数量 × 单位产量\n例如配置§Y4§!、单位产量§Y1.25§!，预计新增§Y5§!单位。\n\n£RUS_nat_text_food£ §4地力疲劳§!：反复集中种植同一种作物会降低其产出，轮换或减少该作物配置可以恢复地力。§4市场饱和§!与§4销售容量§!则属于售价因素：连续集中配置会压价，同一种作物的累计出口超出销售容量后，超出部分逐级折价。\n\n£RUS_nat_text_stock£ §4内需与储备§!：粮食为小麦与黑麦合计，纺织原料为亚麻与棉花合计，甜菜单独计算。先满足内需、留下选定储备，再按指定作物交付整份订单；剩余库存最后截断上限并扣除损耗。\n\n£RUS_nat_text_income£ §4预计出口收入§!：按公开条件估算可交付订单的经济盈余，包含可用旧库存。自用作物只计入国内供给；无可交付订单时收入显示§Y0§!。\n\n预计出口收入 = 各可交付订单预计收入之和\n单笔收入 = 交付数量 × 基价 × 适用售价倍率\n\n作物基价§Y1000§!，农机基价§Y150§!；售价倍率计入条约、饱和与超额折价，并限制在§Y40%—150%§!。每行是该作物收入，底部总览另含农机。',
    '£RUS_nat_text_food£ §4Unit yield§!: estimated physical crops from §Y1§! allocation, including season, soil fatigue, average machinery coverage, public bonuses and partial-quarter scaling.\n\nExpected harvest = allocation x unit yield\n§Y4§! allocation at §Y1.25§! yields §Y5§! units.\n\n£RUS_nat_text_food£ §4Soil fatigue§!: repeated concentrated planting reduces output; rotating or reducing that crop allows recovery. §4Saturation§! and §4sales capacity§! affect prices: repeated concentration lowers prices; exports beyond a crop\'s sales capacity receive marginal discounts.\n\n£RUS_nat_text_stock£ §4Domestic needs and reserves§!: wheat and rye share food needs; flax and cotton share fibre needs; beet stands alone. Meet domestic needs, keep selected reserves, then deliver whole orders of their specified crop. Remaining stock is capped and then spoils.\n\n£RUS_nat_text_income£ §4Estimated export income§!: surplus from deliverable orders under public conditions, including available old stocks. Domestic use counts towards supply; no deliverable orders means §Y0§! income.\n\nEstimated export income = sum of deliverable order estimates\nOrder income = quantity x base price x applicable price multiplier\n\nBase prices: crops §Y1000§!, machinery §Y150§!. Treaty bonuses, saturation and marginal discounts apply within §Y40%–150%§!. Crop rows show their own income; the footer also includes machinery.',
    '£RUS_nat_text_food£ §4Урожай на единицу§!: ожидаемый выпуск при §Y1§! единице плана с учётом сезона, истощения, среднего покрытия техникой, открытых бонусов и доли квартала.\n\nОжидаемый урожай = план x урожай на единицу\nПлан §Y4§! при §Y1.25§! даёт §Y5§! единиц.\n\n£RUS_nat_text_food£ §4Истощение почвы§!: повторная концентрация посевов снижает урожай; смена или сокращение культуры восстанавливает почву. §4Насыщение§! и §4ёмкость сбыта§! влияют на цены: повторная концентрация снижает цену, экспорт сверх ёмкости получает поэтапную скидку.\n\n£RUS_nat_text_stock£ §4Нужды и резервы§!: пшеница и рожь обеспечивают зерно, лён и хлопок — волокно, свёкла учитывается отдельно. Сначала снабжение, затем выбранный резерв и полные заказы указанной культуры. Остатки ограничиваются складом, после чего вычитаются потери.\n\n£RUS_nat_text_income£ §4Ожидаемый доход§!: профицит от выполнимых заказов при открытых условиях, включая старые запасы. Внутреннее потребление учитывается в снабжении; без выполнимого заказа доход §Y0§!.\n\nДоход экспорта = сумма оценок выполнимых заказов\nДоход заказа = количество x базовая цена x множитель цены\n\nБаза: культуры §Y1000§!, техника §Y150§!. Договор, насыщение и скидки учитываются в пределах §Y40%–150%§!. Строка культуры показывает её доход; итог также включает технику.');
  const option=(name,body='')=>`option = { name = ${name} ${body} }\n`;
  const prod=option('RUS_nat_event_production','set_variable = { RUS_nat_page = 1 } RUS_nat_refresh = yes');
  const ledger=option('RUS_nat_event_ledger','RUS_nat_refresh = yes country_event = { id = RUS_national_agriculture.5 }');
  const conditions=option('RUS_nat_event_conditions','country_event = { id = RUS_national_agriculture.6 }');
  const indicators=option('RUS_nat_event_indicators','country_event = { id = RUS_national_agriculture.7 }');
  const guide=option('RUS_nat_event_guide','country_event = { id = RUS_national_agriculture.2 }');
  const close=option('RUS_nat_event_close');
  const event=(num,options)=>`country_event = { id = ${id(num)} title = ${id(num)}.t desc = ${id(num)}.d picture = GFX_report_event_RUS_ustinov is_triggered_only = yes ${options} }\n`;
  write('events/RUS_national_agriculture_events.txt','add_namespace = RUS_national_agriculture\n'+
    event(1,prod+ledger+option(id(1)+'.a'))+event(2,conditions+prod+ledger+close)+event(3,prod+ledger+close)+
    event(4,prod+ledger+option('RUS_nat_event_confirm','trigger = { has_country_flag = RUS_nat_enabled NOT = { has_country_flag = RUS_agri_allocation_locked } } set_country_flag = RUS_nat_manual_plan RUS_agri_confirm_allocation = yes RUS_nat_refresh = yes')+close)+event(5,prod+close)+
    event(6,indicators+guide+close)+event(7,conditions+guide+close));
};
